language: ruby
rvm: 1.9.3
before_script:
  - rm -rf test/
script: 
  - bundle exec rake test
after_script:
  - bin/calatrava create test --dev
  - rvm rvmrc trust test/
  - cd test
  - bundle install
  - bundle exec rake bootstrap
  - bundle exec rake kernel:spec
  - bundle exec rake web:build
